### ISSUE TITLE
linker script of each core in Arduino

### ISSUE THREAD

**Issue by vtpgit** [adailtonjn68/STM32H7xx_inter-core_data_share#1]
>> Add the following in linker script of each core

Hello, great work!

Could you please explain how to add the linker script to Arduino IDE?

I would like to use this within the Arduino framework.

Thank you!

**Comment by adailtonjn68** [comment]
I cannot help much since I don't use the Arduino IDE. Although, I believe it is simple to do that.
I am using Linux. I can find the linker script in ~/.arduino15/packages/STMicroelectronics/hardware/stm32/2.8.0/variants/
Which OS are you using?
Can you test and verify if it works?

**Comment by vtpgit** [comment]
> Which OS are you using

Windows Server 19.

I'm checking now.

The D3 section is already there, no need to add it. Screenshot below:

In directory

C:\Users\Administrator\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.8.0\variants\STM32H7xx\H742X(G-I)H_H743X(G-I)H_H745X(G-I)H_H747X(G-I)H_H750XBH_H753XIH_H755XIH_H757XIH

![image](https://github.com/user-attachments/assets/41f48c4f-15d4-4327-846b-612512a4487b)

The second part, with the .shared assert must be added, as it doesn't exist.

![image](https://github.com/user-attachments/assets/8c9880c1-7138-4019-b676-9c632c7d93e2)

I will now check the second issue you responded to.

Thank you.

**Comment by adailtonjn68** [comment]
For the time, I believe this issue is solved. If you have other problems, please open another issue.
